### ISSUE TITLE
Elsol should have an open-source license

### ISSUE THREAD

**Issue by relwell** [findmypast/elsol#6]
We should add a license to this project that reflects its character as open-source software.

**Comment by boonious** [comment]
Yup, shall commit a licence to the source later.

**Comment by boonious** [comment]
`elsol` now in Apache 2 license.

**Comment by relwell** [comment]
@boonious sorry to be a bug on this one, but it looks like the license isn't completed: https://github.com/findmypast/elsol/blob/master/LICENSE#L196
