### ISSUE TITLE
New changes to Elsol should push to Hex automatically

### ISSUE THREAD

**Issue by relwell** [findmypast/elsol#7]
This can be done once we configure Travis CI against findmypast/elsol. This will involve updating Travis.yml to publish to Hex.

Useful docs:
http://trivelop.de/2014/10/17/continous-docs-in-elixir-with-hex-and-travis/

(note that I won't be able to do this if the project is under the findmypast organization)

**Comment by relwell** [comment]
@boonious just wanted to ping you on this -- I will probably hold off on adding more functionality until the project is integrated with some CI solution. since this project is open-source, travis should build it for free. i think what we want is for pushes/merges to to master to result in a push to hex, with the travis build number appended as the patch version. what do you think?

**Comment by boonious** [comment]
@relwell hey I finally have times to look into this. Yes, I agree we need to a lot of tests sorted and CI working. If you're still up for contributing then we will add you to the contributor list.

**Comment by relwell** [comment]
Sounds good -- please go ahead and add me. I will also need bits associated with your TravisCI account to configure pre-merge verification.

**Comment by boonious** [comment]
@relwell sorry, I just noticed your response above! Wasn't ping and obviously too busy to check this page.. I'm going to see about this and TravisCI next week. Boon

**Comment by relwell** [comment]
Cleaning out my open issues.
